### ISSUE TITLE
OSError: I2C bus error

### ISSUE THREAD

**Issue by GeirFrimann** [robert-hh/BME280#1]
I'm trying this library on Pycom gpy and fipy and Adafruit breakout board (https://www.adafruit.com/product/2652), but gets error OSError: I2C bus error:

`from machine import I2C
import bme280_int
i2c = I2C(0,mode=I2C.MASTER,pins=('P9','P10'),baudrate=1000000)
print(i2c.scan())
#REPL [119]
bme = bme280_int.BME280(i2c=i2c)
#REPL File "/flash/lib/bme280_int.py", line 88, in __init__
OSError: I2C bus error`
Same issue with bme280_float.py, but on line 84.

**Comment by robert-hh** [comment]
The result of i2c.scan tells, that the address of your bme280 module is 119. The default in the driver is 118. So you have to specify the address in instantiating the driver
`bme = bme280_int.BME280(i2c=i2c, address=119)`

**Comment by GeirFrimann** [comment]
Ahh, tanks, now it works!
