### ISSUE TITLE
strange values

### ISSUE THREAD

**Issue by ser** [robert-hh/BME280#11]
hi, i am getting strange values from my sensor:

```
>>> from machine import Pin, I2C
>>> i2c = I2C(0, scl=Pin(22), sda=Pin(21))
>>> i2c.scan()
[118]
>>> import bme280
>>> bme = bme280.BME280(i2c=i2c)
>>> print(bme.values)
('-40.00C', '505.52hPa', '48.27%')
>>> print(bme.values)
('-40.00C', '505.28hPa', '48.27%')
>>> print(bme.values)
('-40.00C', '505.39hPa', '48.29%')
```

do you think the sensor might be broken or there are some special tricks to get correct values? :)

**Comment by robert-hh** [comment]
That looks indeed strange. Can you show the result of calling:
```
from machine import Pin, I2C
import bme280
i2c = I2C(0, scl=Pin(22), sda=Pin(21))
bme = bme280.BME280(i2c=i2c)
result = array("i", [0, 0, 0])
bme.read_raw_data(result)
print(result)
print(i2c.readfrom_mem(0x76, 0xd0, 1))
```
Are you sure it's and BME280 and not a BMP280? What is the fine print on the sensor chip (the small metal box with a hole)?

**Comment by ser** [comment]
On the sensor it reads BME/BMP280 :) :) :) 

I have swapped for https://github.com/dafvid/micropython-bmp280 but the results are similar:

```
>>> print(bmp.temperature)
-142.44
>>> print(bmp.pressure)
51823.52
```

in your code above, which array you mean?

```
>>> result = array("i", [0, 0, 0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'array' isn't defined
>>> import array
>>> result = array("i", [0, 0, 0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object isn't callable
```

**Comment by robert-hh** [comment]
Sorry. The code should be
```
from machine import Pin, I2C
import bme280
from array import array
i2c = I2C(0, scl=Pin(22), sda=Pin(21))
bme = bme280.BME280(i2c=i2c)
result = array("i", [0, 0, 0])
bme.read_raw_data(result)
print(result)
print(i2c.readfrom_mem(0x76, 0xd0, 1))

```

**Comment by ser** [comment]
```
>>> print(result)
array('i', [0, 526516, 38608])
>>> print(i2c.readfrom_mem(0x76, 0xd0, 1))
b'`'
```

**Comment by robert-hh** [comment]
So it's indeed a BME280, but the raw temperature reading looks wrong, being 0. That affects the pressure result as well. So unless the sensor is placed at >5500 m above sea level and temperatures < -40°C, the sensor looks broken.

**Comment by ser** [comment]
Thank you very much, Robert, I'm ordering a replacement then.

**Comment by robert-hh** [comment]
b.t.w.. When I asked for the writing on the sensor, I asked for the imprint on this little component:
![grafik](https://user-images.githubusercontent.com/12476868/212536210-346d46a7-231a-4f13-a850-7e5af048acb3.png)
