### ISSUE TITLE
Sea level inconsistency

### ISSUE THREAD

**Issue by pslootweg** [robert-hh/BME280#14]
In **both** libraries during initialisation the code defaults

`self.__sealevel = 101325`

But the altitude calculations clearly expect distinct values for float and int.

**float:**
```
p = 44330 * (1.0 - pow(self.read_compensated_data()[1] /
                                   self.__sealevel, 0.1903))
```

**int:** (NB **/256** term)
```
p = 44330 * (1.0 - pow((self.read_compensated_data()[1] / 256) /
                                   self.__sealevel, 0.1903))
```

This is reflected in the fact that the

```
    @sealevel.setter
    def sealevel(self, value):
        if 30000 < value < 120000:  # just ensure some reasonable value
            self.__sealevel = value
```

vs

```
    @sealevel.setter
    def sealevel(self, value):
        if 300 < value < 1200:  # just ensure some reasonable value
            self.__sealevel = value
```

I've been trying to figure out what's right and what's wrong, but couldn't decide.

**Comment by robert-hh** [comment]
Altitude requires the sealevel pressure being set to the proper value. You have to get that value from your local weather station and to set using the sealevel property setter, e.g. `bme280.sealevel = value`. The BME280 just measure the local pressure. The weather stations usually report the sealevel pressure.

**Comment by pslootweg** [comment]
Let me put it another way, is 'sealevel' the pressure Pa or hPa?

In the int library the code uses measured pressure as (self.read_compensated_data()[1] / 256) (which is neither Pa or hPa) but sealevel is constrained to a value from 300-1200 'something' through the setter.

In the float library the code uses measured pressure as (self.read_compensated_data()[1]) (which is Pa) and sealevel is constrained to a value from 30000-120000 - presumably Pa.

**Comment by robert-hh** [comment]
The int version should return Pa with bme.values, and Pa * 256 with bme.read_compensated_data(). Given that, the value range for sealevel should be 30000 - 120000, although a value of 30000 is surely strange.

**Comment by robert-hh** [comment]
Updated.
