### ISSUE TITLE
setting intial sleep mode within constructor comparing int-version and float-version

### ISSUE THREAD

**Issue by nkrba** [robert-hh/BME280#16]
https://github.com/robert-hh/BME280/blob/32b9fe96418e68a85b170ee662d41747d52a14f2/bme280_int.py#L118

curious why `self._l1_barray` is not written to memory in the next line, while `bme280_float.py` does so (?)

also as per the `bme280_int.py` code, line 119-120, `0x3c` is `00111100`, hence we are setting oversampling ×1 for Temperature (first three msb `001`) but oversampling ×16 for Pressure (next three msb `111`) as per Table 22, Page 29 from the datasheet below?
https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme280-ds002.pdf 

and if `bme280_int.py` version does not need this, this line could be removed (because none of the other functions seem to use the value stored in `self._l1_barray` in this line) ?

**Comment by robert-hh** [comment]
Thank you for your post. That looks not right. Instead of the constant, the _l1_barray sour be written to configure the mode as supplied in the constructor.
Edir: Although, the ony important part of the write is the SLEEP flag. The modes will be set again in read_raw_data.

**Comment by nkrba** [comment]
Yes had seen read_raw_data but wanted to know if the constructor setting will affect things. Otherwise all good as we seem to be using the forced mode to obtain the data, thanks again!

**Comment by nkrba** [comment]
Also one observation is, sometimes after 5 minutes of BME280's sleep, a read seem to return the same values as before. But an immediate re-read within a few seconds updates the values. Not sure why but wanted to record this observation if there has been similar experiences elsewhere
