### ISSUE TITLE
I2C bus error

### ISSUE THREAD

**Issue by jhn4** [robert-hh/BME280#3]
I'm using pycom's FiPy and got the I2C bus error when using your example code on the the combined CSS811/BME280 enviromental sensor. I fixed it however by changing the BME280 default adress from 0x76 to 0x77, i don't know if it's the combined sensor that have this changed or if the mistake is in your code. However maybe you can add a comment or somthing to make life easier for other people!
Chnaged to this:
# BME280 default address.
BME280_I2CADDR = 0x77

//J

**Comment by robert-hh** [comment]
The I2C-Address of the BME280 is 0x76 or 0x77, depending on the value of its SDO pin. That one is sometimes hardwired, sometimes available on a breakout board pin. At the breakout board I used a solder bridge is foreseen to change the address. It is common for I2C devices to have several configurable addresses.
