### ISSUE TITLE
What licence is this code offered under?

### ISSUE THREAD

**Issue by LukePrior** [robert-hh/BME280#5]
Hi,

I was just wondering what software licence this code is offered under as I was considering creating a localised guide for my region.

Here is a guide on how to set licence type: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

MIT would be great.

Cheers

**Comment by robert-hh** [comment]
The license is contained in the header of the source code files, as they were when I ported them from a Adafruit version. Adafruit used the MIT license code, and so it's there. The driver has quite a history, including influence from a BOSCH C code, so it's hard to tell what the actual license situation is.  But all sources I found contained the MIT license text. So I think it's fine to assume a MIT state of license.

**Comment by LukePrior** [comment]
Cool cheers.
